image:
  file: .gitpod.Dockerfile

gitlab:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    prebuild: echo "Prebuild!"
    command: cd todolist

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

vscode:
  extensions:
    - jebbs.plantuml@2.13.12:q7DiD6H5NTesaWYIXmeMMQ==
    - vsls-contrib.codetour@0.0.37:n/LcXr1DIqz+xFGficwDHA==
