image: maven:3.8.3-openjdk-17

stages:
  - test
  - build

test:
  stage: test
  script:
    - cd todolist; mvn test -B -P headless

build:
  stage: build
  when: manual
  script:
    - cd todolist; mvn install -B -P headless
