image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 14.0.2.j9-adpt
    command: cd todolist

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

vscode:
  extensions:
    - redhat.java@0.66.0:isbEqq9wcF5w98K9rJHzbA==